# Based on: https://github.com/airbnb/css
files:
  ignore: '**/vendor/**'

options:
  formatter: stylish
  merge-default-rules: true

rules: # All rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules
  bem-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: ^(?!js-).*
      convention-explanation: should not be written in the form js-*
  extends-before-declarations: 0
  extends-before-mixins: 0
  force-pseudo-nesting: 0
  function-name-format: 1
  leading-zero: 0
  mixin-name-format: 1
  mixins-before-declarations: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-extends: 0
  no-qualifying-elements: 0
  no-invalid-hex: 2
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 0
  quotes:
    - 1
    - style: double
  variable-name-format: 1
